<?PHP
////////////////////////////////////////////////////////////////////////////////
//                                                                            //
//   Copyright (C) 2000  Phorum Development Team                              //
//   http://www.phorum.org                                                    //
//                                                                            //
//   This program is free software. You can redistribute it and/or modify     //
//   it under the terms of the Phorum License Version 1.0.                    //
//                                                                            //
//   This program is distributed in the hope that it will be useful,          //
//   but WITHOUT ANY WARRANTY, without even the implied warranty of           //
//   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.                     //
//                                                                            //
//   You should have received a copy of the Phorum License                    //
//   along with this program.                                                 //
////////////////////////////////////////////////////////////////////////////////

// user settings
  $use_security=1;

/////////////////////////////////////////////////////////

  $admin=1;
  $fullaccess=true;
  if(!isset($login)) $login=0;
  
  // Check that the page given is a forum level page if num given
  // otherwise people could bypass security by giving a num value
  // and a moderator password on say Master Settings.
  $modpages='managemenu,manage,advdel,quickedit,quickdel,edit,props,easyadmin,quickapp,datedel';
  if(isset($num) && !@strstr($modpages,$page) && $login!=1){
    $forum_id=$num;
    $num=0;
  }

  chdir("/home/freshports.org/www/phorum");
  include "common.php";
  $myname=$admin_page;

  if($use_security){
    include "$admindir/login.php";
    check_login();
  }
  
  function writefile($forum='', $main=false){
    GLOBAL $DB, $q, $inf_path,$inf_file,$inf_back,$down,$dbType,$dbName,$dbUser,$dbPass,$dbServer,$DefaultDisplay,$DefaultEmail,$SortForums,$Password,$UseCookies;
    GLOBAL $forum_url,$ext,$forum_page,$list_page,$search_page,$read_page,$post_page,$violation_page,$down_page,$admindir;
    GLOBAL $default_table_width,$default_table_header_color,$default_table_header_font_color,$default_table_body_color_1,$default_table_body_font_color_1,$default_table_body_color_2,$default_table_body_font_color_2,$default_nav_color,$default_nav_font_color,$default_lang;
    
    if($main!=false || $forum=='all' || $forum==''){
//      @unlink($inf_back);
      if(copy($inf_file, $inf_back)){
        QueMessage("$inf_file backed up to $inf_back");
      }
      else{
        QueMessage("$inf_file could not be backed up");
      }
      $x=0;
    
      if($dbType=="") $dbType=$DB->type;
    
      $sSQL="Select count(*) as count from forums where active=1";
      $q->query($DB, $sSQL);
      $rec=$q->getrow();

      $active_count='0';
      if(isset($rec["count"])){
        $active_count="$rec[count]";
      }      

      $data="<?PHP\n";
      $data.="// DO NOT EDIT THIS FILE.  USE THE ADMIN\n\n";
      if($down==1){
        $data.="  if(\$admin!=1){\n";      
        $data.="    Header(\"Location: $forum_url/$down_page.$ext\");\n";
        $data.="    exit();\n";
        $data.="  }\n";            
        $data.="  \$down=1;\n\n";            
      }
      $data.="// initialize database variables\n";
      $data.="  \$dbName='$dbName';\n";            
      $data.="  \$dbUser='$dbUser';\n";            
      $data.="  \$dbPass='$dbPass';\n";            
      $data.="  \$dbServer='$dbServer';\n";
      $data.="\n";
      $data.="// create database classes\n";
      $data.="  if ( defined( \"_DB_LAYER\" ) ){\n";
      $data.="    \$DB = new db();\n";
      $data.="    \$DB->open(\$dbName, \$dbServer, \$dbUser, \$dbPass);\n";
      $data.="    \$q = new query(\$DB); //dummy query for generic operations\n";
      $data.="  }\n";
      $data.="\n";
      $data.="// master information\n";
      $data.="  \$Password='$Password';\n";
      $data.="  \$DefaultDisplay='$DefaultDisplay';\n";
      $data.="  \$DefaultEmail='$DefaultEmail';\n";
      $data.="  \$UseCookies='$UseCookies';\n";
      $data.="  \$SortForums='$SortForums';\n";
      $data.="  \$ActiveForums='$active_count';\n";
      $data.="\n";  
      $data.="  \$forum_url='$forum_url';\n";  
      $data.="  \$ext='$ext';\n";
      $data.="  \$forum_page='$forum_page';\n";
      $data.="  \$list_page='$list_page';\n";
      $data.="  \$search_page='$search_page';\n";
      $data.="  \$read_page='$read_page';\n";
      $data.="  \$post_page='$post_page';\n";
      $data.="  \$violation_page='$violation_page';\n";
      $data.="  \$down_page='$down_page';\n";
      $data.="  \$default_lang='$default_lang';\n";
      $data.="  \$default_table_width='$default_table_width';\n";
      $data.="  \$default_table_header_color='$default_table_header_color';\n";
      $data.="  \$default_table_header_font_color='$default_table_header_font_color';\n";
      $data.="  \$default_table_body_color_1='$default_table_body_color_1';\n";
      $data.="  \$default_table_body_font_color_1='$default_table_body_font_color_1';\n";
      $data.="  \$default_table_body_color_2='$default_table_body_color_2';\n";
      $data.="  \$default_table_body_font_color_2='$default_table_body_font_color_2';\n";
      $data.="  \$default_nav_color='$default_nav_color';\n";
      $data.="  \$default_nav_font_color='$default_nav_font_color';\n";
      $data.="\n";
      $data.="?>";

      $fp = fopen("$inf_file", "w");
      fputs($fp, $data);
      fclose($fp);
    }

    if($forum!=''){
      $sSQL="Select * from forums";
      if($forum!='all') $sSQL.=" where id=$forum";
      $q->query($DB, $sSQL);
      $rec=(object)$q->getrow();
      While(isset($rec->id)){
        if(!get_cfg_var("magic_quotes_runtime")){
          $rec->name = str_replace("'", "\\'", $rec->name);
          $rec->description = str_replace("'", "\\'", $rec->description);
          $rec->staff_host = str_replace("'", "\\'", $rec->staff_host);
        }
        $data ="<?PHP\n";
        $data.='  // $rec->name forum'."\n";
        $data.="  \$ForumId=$rec->id;\n";
        $data.="  \$ForumActive='$rec->active';\n";
        $data.="  \$ForumName='$rec->name';\n";
        $data.="  \$ForumDescription='$rec->description';\n";
        $data.="  \$ForumFolder='$rec->folder';\n";
        $data.="  \$ForumParent='$rec->parent';\n";
        if($rec->folder!="1"){
          $rec->folder=="0";
        }
        if($rec->folder=="0"){
          $data.="  \$ForumDisplay='$rec->display';\n";
          $data.="  \$ForumTableName='$rec->table_name';\n";
          $data.="  \$ForumModeration='$rec->moderation';\n";
          $data.="  \$ForumModEmail='$rec->mod_email';\n";
          $data.="  \$ForumModPass='$rec->mod_pass';\n";
          $data.="  \$ForumEmailList='$rec->email_list';\n";
          $data.="  \$ForumEmailReturn='$rec->email_return';\n";
          $data.="  \$ForumCheckDup='$rec->check_dup';\n";
          $data.="  \$ForumMultiLevel='$rec->multi_level';\n";
          $data.="  \$ForumCollapse='$rec->collapse';\n";
          $data.="  \$ForumFlat='$rec->flat';\n";
          $data.="  \$ForumStaffHost='$rec->staff_host';\n";
          $data.="  \$ForumLang='$rec->lang';\n";
          $data.="  \$ForumAllowHTML='$rec->html';\n";
          $data.="  \$ForumTableWidth='$rec->table_width';\n";
          $data.="  \$ForumTableHeaderColor='$rec->table_header_color';\n";
          $data.="  \$ForumTableHeaderFontColor='$rec->table_header_font_color';\n";
          $data.="  \$ForumTableBodyColor1='$rec->table_body_color_1';\n";
          $data.="  \$ForumTableBodyFontColor1='$rec->table_body_font_color_1';\n";
          $data.="  \$ForumTableBodyColor2='$rec->table_body_color_2';\n";
          $data.="  \$ForumTableBodyFontColor2='$rec->table_body_font_color_2';\n";
          $data.="  \$ForumNavColor='$rec->nav_color';\n";
          $data.="  \$ForumNavFontColor='$rec->nav_font_color';\n";
        }
        $data.="\n?>";
        $fp = fopen("$admindir/forums/$rec->id.php", "w");
        fputs($fp, $data);
        fclose($fp);
        $rec=(object)$q->getrow();
      }
    }
  }
  
  function get_html_value(){
    GLOBAL $html_all,$html_style,$html_font,$html_li,$html_img,$html_a;

    if($html_all==1){
      $html="Y";
    }
    else{
      if($html_style==1){
        $html[]="b";
        $html[]="i";
        $html[]="u";
      }
      if($html_font==1) $html[]="font";
      if($html_li==1){
        $html[]="ol";
        $html[]="ul";
        $html[]="li";
      }
      if($html_img==1) $html[]="img";
      if($html_a==1) $html[]="a";
      if(is_array($html)){
        $html=implode("|", $html);
      }
      else{
        $html="N";
      }
    }
    return $html;
  }

  function QueMessage($m){
    GLOBAL $message;
    if($message)     $message.="\\n";
    $message.="$m";
  }   

  function DropForum($f, $table){
    GLOBAL $q, $DB, $admindir;

    $q->getrow();
    $sSQL="DROP TABLE $table";
    $q->query($DB, $sSQL);
    $sSQL="DROP TABLE $table"."_bodies";
    $q->query($DB, $sSQL);
    $DB->drop_sequence($table);
    $sSQL="Delete from forums where id=$f";
    $q->query($DB, $sSQL);      
    @unlink("$admindir/forums/$f.php");
    
  }

  function DropFolder($f){
    GLOBAL $q, $DB, $admindir;

    $sSQL="Select id, folder, table_name from forums where parent=$f";
    $q->query($DB, $sSQL);
    while($rec=$q->getrow()){
      if($rec["folder"]){
        DropFolder($rec["id"]);
      }
      else{
        DropForum($rec["id"], $rec["table_name"]);
      }
    }
    $sSQL="Delete from forums where parent=$f";
    $q->query($DB, $sSQL);    
    $sSQL="Delete from forums where id=$f";
    $q->query($DB, $sSQL);    
    @unlink("$admindir/forums/$f.php");

  }

  switch ($action) {
    case "pass":
      // Change the master password
      if($newPassword==$confirm){
        QueMessage("Password Changed.");
        $Password=$newPassword;
        writefile();
      }
      else{
        QueMessage("Passwords do not match.");
        $page=$frompage;
      }
      break;
    case "activate":
      // activate the current forum
      $sSQL="Update forums set active=1 where id=$num";
      $q->query($DB, $sSQL);
      $ForumActive=1;
      writefile($num, true);
      break;
    case "deactivate":
      // deactivate the current forum
      $sSQL="Update forums set active=0 where id=$num";
      $q->query($DB, $sSQL);
      $ForumActive=0;
      writefile($num, true);
      break;
    case "drop":
      // drop the current forum/folder
      $sSQL="Select table_name, folder from forums where id=$forum_id";
      $q->query($DB, $sSQL);
      $rec=$q->getrow();
      if($rec["folder"]==0){
        DropForum($forum_id, $rec["table_name"]);
        QueMessage("Forum dropped.");
      }
      else{
        DropFolder($forum_id);
        QueMessage("Folder dropped.");
      }
      break;
    case "seq":
      $sSQL="Select max(id) as id from ".$ForumTableName;
      $q->query($DB, $sSQL);
      if($q->numrows()){
        $id=$q->field("id", 0);
        $ret=$DB->reset_sequence($ForumTableName, $id+1);
        if($ret==0){
          QueMessage("Sequence reset to $id.");
        }
        else{
          QueMessage("There was an error resetting the sequence.");
        }
      }
      else{
        QueMessage("Sequence not set, forum empty.");
      }
      break;
    case "stop":
      $down=1;
      writefile();
      QueMessage("Phorum has been stopped.");
      break;
    case "start":
      $down=0;
      writefile();
      $step=0;
      QueMessage("Phorum has been started.");
      break;
    case "build":
      writefile("all");
      QueMessage("All files rebuilt.");
      break;

    case "db":
      $dbName=$new_dbName;
      $dbUser=$new_dbUser;
      $dbPass=$new_dbPass;
      $dbServer=$new_dbServer;
      $dbType=$new_dbType;
      writefile();
      QueMessage("The Database Settings have been updated.");
      break;
    case "global":
      $DefaultDisplay=$new_DefaultDisplay;
      $DefaultEmail=$new_DefaultEmail;
      $UseCookies=$new_UseCookies;
      $SortForums=$new_SortForums;
      $default_lang=$new_default_lang;
      writefile();
      QueMessage("The HTML properties have been updated.");
      break;      
    case "files":
      if(substr($new_forum_url, -1)=="/") $new_forum_url=substr($new_forum_url, 0, -1);
      $forum_url=$new_forum_url;
      $ext=$new_ext;
      $forum_page=$new_forum_page;
      $list_page=$new_list_page;
      $search_page=$new_search_page;
      $read_page=$new_read_page;
      $post_page=$new_post_page;
      $violation_page=$new_violation_page;
      $down_page=$new_down_page;
      writefile();
      QueMessage("The Files/Paths settings have been updated.");
      break;      
    case "html":
      $default_table_width=$new_default_table_width;                                                                                                                                                                                                                                                                                   $default_table_width=$new_default_table_width;
      $default_table_header_color=$new_default_table_header_color;
      $default_table_header_font_color=$new_default_table_header_font_color;
      $default_table_body_color_1=$new_default_table_body_color_1;
      $default_table_body_font_color_1=$new_default_table_body_font_color_1;
      $default_table_body_color_2=$new_default_table_body_color_2;
      $default_table_body_font_color_2=$new_default_table_body_font_color_2;
      $default_nav_color=$new_default_nav_color;
      $default_nav_font_color=$new_default_nav_font_color;
      writefile();
      QueMessage("The HTML properties have been updated.");
      break;      
    case "edit":
      if(!get_cfg_var("magic_quotes_gpc")){
        $author = addslashes($author);
        $email = addslashes($email);
        $subject = addslashes($subject);
        $body = addslashes($body);
      }
      $sSQL="Update $ForumTableName set author='$author', email='$email', subject='$subject' where id=$id";
      $q->query($DB, $sSQL);
      $sSQL="Update ".$ForumTableName."_bodies set body='$body' where id=$id";
      $q->query($DB, $sSQL);
      QueMessage("Message $id updated!");
      break;
    case "del":
      if($type=="quick"){
        $sSQL = "Select id from $ForumTableName where id in ($id) and id=thread";
        $q->query($DB, $sSQL);
        $rec=$q->getrow();
        $delthreads='';
        While($rec){
          if($delthreads) $delthreads.=',';
          $delthreads.=$rec["id"];
          $rec=$q->getrow();
        }
        
        if(strstr($id, ",")){
          $ids=explode(",", $id);
        }
        else{
          $ids[0]=$id;
        }
        $cnt=count($ids);
        $delids='';
        for($x=0;$x<$cnt;$x++){
          if(!strstr($delthreads, $ids[$x])){
            if($delids) $delids.=',';
            $delids.=$ids[$x];
          }
        }         
      }
      else{
        if(is_array($threadlist)){
          $delthreads=implode(",", $threadlist);
        }
        else{
          $delthreads="";
        }
        if(is_array($idlist)){
          $delids=implode(",", $idlist);
        }
        else{
          $delids="";
        }
      }
      if($delids){
        $sSQL = "Delete from $ForumTableName where id in ($delids)";
        $q->query($DB, $sSQL);
        $sSQL = "Delete from ".$ForumTableName."_bodies where id in ($delids)";
        $q->query($DB, $sSQL);
        QueMessage("Id(s) $delids deleted!<br>");
      }
      if($delthreads){        
        $sSQL = "Delete from $ForumTableName where thread in ($delthreads)";
        $q->query($DB, $sSQL);
        $sSQL = "Delete from ".$ForumTableName."_bodies where thread in ($delthreads)";
        $q->query($DB, $sSQL);
        $message.="Thread(s) $delthreads deleted!";
      }
      break;
    case "datedel":
      if($dateopt=="="){
        $cond="LIKE '$date%'";
      }
      else{
        $cond="$dateopt '$date'";
      }
      $sSQL="Select thread from $ForumTableName where thread=id and datestamp $cond";
      $q->query($DB, $sSQL);
      if($err=$q->error()){
        QueMessage("$err<br>$sSQL");
      }
      elseif($q->numrows()!=0){
        $rec=$q->getrow();
        $threads='';
        while(is_array($rec)){
          if($threads!='') $threads.=", ";
          $threads.="$rec[thread]";
          $rec=$q->getrow();
        }
        $sSQL="Select count(*) as count from $ForumTableName where thread in ($threads)";
        $q->query($DB, $sSQL);
        $rec=$q->getrow();
        $count=$rec["count"];
        if($err=$q->error()){
          QueMessage("$err<br>$sSQL");
        }
        $sSQL="Delete from $ForumTableName where thread in ($threads)";
        $q->query($DB, $sSQL);
        if($err=$q->error()){
          QueMessage("$err<br>$sSQL");
        }
        else{
          QueMessage("$count message(s) deleted.");
        }        
      }
      else{
        QueMessage("No messages selected for deletion.");
      }
      break;
    case "add":
      if(!$table_exists && !$folder) $err=create_table($DB, "main", $table);
      if($err==""){
        if(!$table_exists && !$folder) $err=create_table($DB, "bodies", $table);
        if($err==""){
          if($name!=""){
            if(($mod_pass!="" && $mod_pass==$mod_pass_2) || $folder){
              $id=$DB->nextid('forums');
              if($id==0){
                $page=$frompage;
                QueMessage("Could not get a new id for the new forum.\nCheck your database settings.");
              }
              else{
                if(!get_cfg_var("magic_quotes_gpc")){
                  $name = str_replace("'", "\\'", $name);
                  $description = str_replace("'", "\\'", $description);
                  $staff_host = str_replace("'", "\\'", $staff_host);
                }
                if(!$folder) {
                  $html=get_html_value();
                  $sSQL="Insert into forums values ('$id', '$name', 0, '$description', '$folder', '$parent', '$display', '$table', '$moderation', '$mod_email', '$mod_pass', '$email_list', '$email_return', '$check_dup', '$multi_level', '$collapsed', '$rflat', '$staff_host', '$lang', '$html', '$table_width', '$table_header_color', '$table_header_font_color', '$table_body_color_1', '$table_body_color_2', '$table_body_font_color_1', '$table_body_font_color_2', '$nav_color', '$nav_font_color')";
                }
                else{
                  $sSQL="Insert into forums (id,name,active,description,folder,parent) values ('$id', '$name', 0, '$description', '$folder', '$parent')";
                }
                $q->query($DB, $sSQL);
                writefile($id);
                QueMessage("$name created [id: $id]");
                $num=$id;
                include "$admindir/forums/$num.php";
              }
            }            
            else{
              $sSQL="drop table $table";
              if(!$table_exists) $q->query($DB, $sSQL);
              $sSQL="drop table $table"."_bodies";
              if(!$table_exists) $q->query($DB, $sSQL);
              QueMessage("Either you did not provide a password or the passwords did not match.");
              $page=$frompage;
            }             
          }
          else{
            $sSQL="drop table $table";
            if(!$table_exists) $q->query($DB, $sSQL);
            $sSQL="drop table $table"."_bodies";
            if(!$table_exists) $q->query($DB, $sSQL);
            QueMessage("You must provide a name for the forum.");
            $page=$frompage;
          }             
        }
        else{
          $sSQL="drop table $table";
          if(!$table_exists) $q->query($DB, $sSQL);
          QueMessage($err);
          $page=$frompage;
        }
      }
      else{
        QueMessage($err);
        $page=$frompage;
      }
      break;
    case "props":
      if($name!=""){
        if($mod_pass!=$mod_pass_2){  
          QueMessage("Either you did not provide a password or the passwords did not match.");
          $page=$frompage;
        }
        else{        
          if(!$ForumFolder){
            if($mod_pass=="") $mod_pass=$ForumModPass;
            if($ForumTableName!=$table && !$ForumFolder){
              $sSQL="ALTER TABLE $ForumTableName"." RENAME $table";
              if(!$table_exists) $q->query($DB, $sSQL);
              $err=$q->error();
              if($err==""){
                $sSQL="ALTER TABLE $ForumTableName"."_bodies RENAME ".$table."_bodies";
                if(!$table_exists) $q->query($DB, $sSQL);
                $err=$q->error();
              }
              if($DB->type=="mysql"){
                $sSQL="ALTER TABLE $ForumTableName"."_seq RENAME ".$table."_seq";
                if(!$table_exists) $q->query($DB, $sSQL);
                $err=$q->error();
              }
            }
          }
          if($err==""){
            if(!get_cfg_var("magic_quotes_gpc")){
              $name = str_replace("'", "\\'", $name);
              $description = str_replace("'", "\\'", $description);
              $staff_host = str_replace("'", "\\'", $staff_host);
            }
            if(!$ForumFolder) {
              $html=get_html_value();
              $sSQL="Update forums set name='$name', description='$description', parent='$parent', display='$display', table_name='$table', moderation='$moderation', mod_email='$mod_email', mod_pass='$mod_pass', email_list='$email_list', email_return='$email_return', check_dup='$check_dup', multi_level='$multi_level', collapse='$collapsed', flat='$rflat', staff_host='$staff_host', lang='$lang', html='$html', table_width='$table_width', table_header_color='$table_header_color', table_header_font_color='$table_header_font_color', table_body_color_1='$table_body_color_1', table_body_color_2='$table_body_color_2', table_body_font_color_1='$table_body_font_color_1', table_body_font_color_2='$table_body_font_color_2', nav_color='$nav_color', nav_font_color='$nav_font_color' where id=$num";
            }
            else{
              $sSQL="Update forums set name='$name', description='$description', parent='$parent' where id=$num";
            }
            $q->query($DB, $sSQL);
            $err=$q->error();
            if($err==""){              
              $ForumName=stripslashes($name);
              writefile($num);
              QueMessage("$ForumName has been updated.");
            }
            else{
              QueMessage($err);
              $page=$frompage;
            }
          }
          else{
            QueMessage($err);
            $page=$frompage;
          }                           
        }
      }
      else{
        QueMessage("You must provide a name for the forum.");
        $option=="edit_prop";
      }             
      break;
    case "moderate":
      if($approved=='Y'){
        $approved='N';
        $word = "hidden";
      }
      elseif($approved=='N'){
        $approved='Y';
        $word = "approved";
      }
      $sSQL="Update $ForumTableName set approved='$approved' where id=$id";
      $q->query($DB, $sSQL);
      $err=$q->error();
      if($err==""){
        QueMessage("Message $id $word.");
      }
      else{
        QueMessage($err);
      }
      break;
  }

  include "$admindir/header.php";

  // If you add pages to the admin that operate at a forum level you need
  // to be sure and add them to the $modpages at the top of this script.
  if($page=="newforum"){
    $page="new";
    $folder="0";
  }
  elseif($page=="newfolder"){
    $page="new";
    $folder="1";
  }

  if($page){
    include "$admindir/pages/$page.php";
  }
  else{
    QueMessage("Sorry, this page is not available when logged in as a forum moderator.");
  }

  if($message){
    echo "<p><span align=\"CENTER\" class=message><font face=\"Arial,Helvetica\" color=\"#800000\"><b>".str_replace('\\n', '<br>', $message)."</b></font></span>\n";
  }
  include "$admindir/footer.php";
?>
