<hr>
<table width="100%" border="0">
<tr>

<td align="center" valign="center"><a href="http://www.apache.org/"><img src="http://freshports.org/images/apache_pb.gif"
alt="powered by apache" border="0" width="259" height="32"></a></td>


<td align="center" valign="center"><a href="http://www.freebsd.org/"><img src="http://freshports.org/images/pbfbsd2.gif"
alt="powered by FreeBSD" border="0" width="171" height="64"></a></td>

<td align="center" valign="center"><a href="http://www.mysql.org/"><img src="http://freshports.org/images/mysql.gif"
alt="powered by mysql" border="0" width="88" height="46"></a></td>

<td align="center" valign="center"><a href="http://www.php3.org/"><img src="http://freshports.org/images/php3.gif"
alt="powered by php3" border="0" width="88" height="31"></a></td>

</tr>
</table>
