CREATE TABLE forums (
  id int(11) DEFAULT '0' NOT NULL,
  name char(50) DEFAULT '' NOT NULL,
  active smallint DEFAULT 0 NOT NULL,
  description char(255) DEFAULT '' NOT NULL,
  folder char(1) DEFAULT '0' NOT NULL,
  parent int DEFAULT 0 NOT NULL,
  display int DEFAULT 0 NOT NULL,
  table_name char(50) DEFAULT '' NOT NULL,
  moderation char(1) DEFAULT 'n' NOT NULL,
  mod_email char(50) DEFAULT '' NOT NULL,
  mod_pass char(50) DEFAULT '' NOT NULL,
  email_list char(50) DEFAULT '' NOT NULL,
  email_return char(50) DEFAULT '' NOT NULL,
  check_dup smallint DEFAULT 0 NOT NULL,
  multi_level smallint DEFAULT 0 NOT NULL,
  collapse smallint DEFAULT 0 NOT NULL,
  flat smallint DEFAULT 0 NOT NULL,
  staff_host char(50) DEFAULT '' NOT NULL,
  lang char(50) DEFAULT '' NOT NULL,
  html char(40) DEFAULT 'N' NOT NULL,
  table_width char(4) DEFAULT '' NOT NULL,
  table_header_color char(7) DEFAULT '' NOT NULL,
  table_header_font_color char(7) DEFAULT '' NOT NULL,
  table_body_color_1 char(7) DEFAULT '' NOT NULL,
  table_body_color_2 char(7) DEFAULT '' NOT NULL,
  table_body_font_color_1 char(7) DEFAULT '' NOT NULL,
  table_body_font_color_2 char(7) DEFAULT '' NOT NULL,
  nav_color char(7) DEFAULT '' NOT NULL,
  nav_font_color char(7) DEFAULT '' NOT NULL,
  PRIMARY KEY (id),
  KEY (name),
  KEY (active),
  KEY (parent)
);