<table BORDER="1" WIDTH="100%">
  <tr>
    <td><code>%M</code> </td>
    <td>Month name (<code>January</code>..<code>December</code>) </td>
  </tr>
  <tr>
    <td><code>%W</code> </td>
    <td>Weekday name (<code>Sunday</code>..<code>Saturday</code>) </td>
  </tr>
  <tr>
    <td><code>%D</code> </td>
    <td>Day of the month with english suffix (<code>1st</code>, <code>2nd</code>, <code>3rd</code>,
    etc.) </td>
  </tr>
  <tr>
    <td><code>%Y</code> </td>
    <td>Year, numeric, 4 digits </td>
  </tr>
  <tr>
    <td><code>%y</code> </td>
    <td>Year, numeric, 2 digits </td>
  </tr>
  <tr>
    <td><code>%a</code> </td>
    <td>Abbreviated weekday name (<code>Sun</code>..<code>Sat</code>) </td>
  </tr>
  <tr>
    <td><code>%d</code> </td>
    <td>Day of the month, numeric (<code>00</code>..<code>31</code>) </td>
  </tr>
  <tr>
    <td><code>%e</code> </td>
    <td>Day of the month, numeric (<code>0</code>..<code>31</code>) </td>
  </tr>
  <tr>
    <td><code>%m</code> </td>
    <td>Month, numeric (<code>01</code>..<code>12</code>) </td>
  </tr>
  <tr>
    <td><code>%c</code> </td>
    <td>Month, numeric (<code>1</code>..<code>12</code>) </td>
  </tr>
  <tr>
    <td><code>%b</code> </td>
    <td>Abbreviated month name (<code>Jan</code>..<code>Dec</code>) </td>
  </tr>
  <tr>
    <td><code>%j</code> </td>
    <td>Day of year (<code>001</code>..<code>366</code>) </td>
  </tr>
  <tr>
    <td><code>%H</code> </td>
    <td>Hour (<code>00</code>..<code>23</code>) </td>
  </tr>
  <tr>
    <td><code>%k</code> </td>
    <td>Hour (<code>0</code>..<code>23</code>) </td>
  </tr>
  <tr>
    <td><code>%h</code> </td>
    <td>Hour (<code>01</code>..<code>12</code>) </td>
  </tr>
  <tr>
    <td><code>%I</code> </td>
    <td>Hour (<code>01</code>..<code>12</code>) </td>
  </tr>
  <tr>
    <td><code>%l</code> </td>
    <td>Hour (<code>1</code>..<code>12</code>) </td>
  </tr>
  <tr>
    <td><code>%i</code> </td>
    <td>Minutes, numeric (<code>00</code>..<code>59</code>) </td>
  </tr>
  <tr>
    <td><code>%r</code> </td>
    <td>Time, 12-hour (<code>hh:mm:ss [AP]M</code>) </td>
  </tr>
  <tr>
    <td><code>%T</code> </td>
    <td>Time, 24-hour (<code>hh:mm:ss</code>) </td>
  </tr>
  <tr>
    <td><code>%S</code> </td>
    <td>Seconds (<code>00</code>..<code>59</code>) </td>
  </tr>
  <tr>
    <td><code>%s</code> </td>
    <td>Seconds (<code>00</code>..<code>59</code>) </td>
  </tr>
  <tr>
    <td><code>%p</code> </td>
    <td><code>AM</code> or <code>PM</code> </td>
  </tr>
</table>

