<?php

  function writefile($forum='', $main=false) {
    global $PHORUM, $DB, $q, $inf_path,$inf_file,$inf_back,$down,$dbName,$dbUser,$dbPass,$dbServer,$DefaultDisplay,$DefaultEmail,$PhorumMailCode,$SortForums,$Password,$UseCookies;
    global $forum_url,$admin_url,$ext,$forum_page,$list_page,$search_page,$read_page,$post_page,$violation_page,$down_page,$attach_page,$admindir;
    global $default_table_width,$default_table_header_color,$default_table_header_font_color,$default_table_body_color_1,$default_table_body_font_color_1,$default_table_body_color_2,$default_table_body_font_color_2,$default_nav_color,$default_nav_font_color,$default_lang;
    global $pho_main, $AllowAttachments, $AttachmentSizeLimit, $AttachmentFileTypes, $AttachmentDir, $MaximumNumberAttachments, $TimezoneOffset, $default_body_color, $default_body_link_color, $default_body_alink_color, $default_body_vlink_color, $HTTP_HOST, $PHP_SELF, $SERVER_PORT;

    if($main!=false || $forum=='all' || $forum==''){
      if(@copy($PHORUM["settings"], $PHORUM["settings_backup"])){
        QueMessage("Changes Saved.");
      }
      else{
        QueMessage("Changes saved but $inf_file could not be backed up.");
      }
      $x=0;

      $active_count='0';

      if(isset($q)){
        $sSQL="Select count(*) as cnt from ".$PHORUM['main_table']." where active=1";
        $q->query($DB, $sSQL);
        $rec=$q->getrow();

        if(!@empty($rec["cnt"])){
          $active_count="$rec[cnt]";
        }
      }

      $data="<?php\n";
      $data.="// DO NOT EDIT THIS FILE.  USE THE ADMIN\n\n";
      $data.="\n";
      $data.="// one-time-set settings\n";
      $data.="  \$PHORUM['main_table']='".$PHORUM['main_table']."';\n";
      $data.="  \$PHORUM['dbtype']='".$PHORUM['dbtype']."';\n";
      $data.="\n";
      $data.="// Global Settings\n";
      $data.="  \$PHORUM['started']=$PHORUM[started];\n";
      $data.="  \$PHORUM['DefaultDisplay']='$DefaultDisplay';\n";
      $data.="  \$PHORUM['DefaultEmail']='$DefaultEmail';\n";
      $data.="  \$PHORUM['PhorumMailCode']='$PhorumMailCode';\n";
      $data.="  \$PHORUM['UseCookies']='$UseCookies';\n";
      $data.="  \$PHORUM['SortForums']='$SortForums';\n";
      $data.="  \$PHORUM['ActiveForums']='$active_count';\n";
      $data.="  \$PHORUM['TimezoneOffset']='$TimezoneOffset';\n";
      $data.="\n";
      $data.="  \$PHORUM['forum_url']='$forum_url';\n";
      // not sure if this will work with SSL on IIS.
      $data.="  \$PHORUM['admin_url']='".($SERVER_PORT==443 ? "https" : "http")."://$HTTP_HOST$PHP_SELF';\n";
      $data.="\n";
      $data.="  \$PHORUM['AllowAttachments']='$AllowAttachments';\n";
      $data.="  \$PHORUM['AttachmentDir']='$AttachmentDir';\n";
      $data.="  \$PHORUM['AttachmentSizeLimit']='$AttachmentSizeLimit';\n";
      $data.="  \$PHORUM['AttachmentFileTypes']='$AttachmentFileTypes';\n";
      $data.="  \$PHORUM['MaximumNumberAttachments']='$MaximumNumberAttachments';\n";
      $data.="\n";
      $data.="  \$PHORUM['ext']='$ext';\n";
      $data.="  \$PHORUM['forum_page']='$forum_page';\n";
      $data.="  \$PHORUM['list_page']='$list_page';\n";
      $data.="  \$PHORUM['search_page']='$search_page';\n";
      $data.="  \$PHORUM['read_page']='$read_page';\n";
      $data.="  \$PHORUM['post_page']='$post_page';\n";
      $data.="  \$PHORUM['violation_page']='$violation_page';\n";
      $data.="  \$PHORUM['down_page']='$down_page';\n";
      $data.="  \$PHORUM['attach_page']='$attach_page';\n";
      $data.="  \$PHORUM['default_lang']='$default_lang';\n";
      $data.="  \$PHORUM['default_body_color']='$PHORUM[default_body_color]';\n";
      $data.="  \$PHORUM['default_body_link_color']='$PHORUM[default_body_link_color]';\n";
      $data.="  \$PHORUM['default_body_vlink_color']='$PHORUM[default_body_vlink_color]';\n";
      $data.="  \$PHORUM['default_body_alink_color']='$PHORUM[default_body_alink_color]';\n";
      $data.="  \$PHORUM['default_table_width']='$PHORUM[default_table_width]';\n";
      $data.="  \$PHORUM['default_table_header_color']='$PHORUM[default_table_header_color]';\n";
      $data.="  \$PHORUM['default_table_header_font_color']='$PHORUM[default_table_header_font_color]';\n";
      $data.="  \$PHORUM['default_table_body_color_1']='$PHORUM[default_table_body_color_1]';\n";
      $data.="  \$PHORUM['default_table_body_font_color_1']='$PHORUM[default_table_body_font_color_1]';\n";
      $data.="  \$PHORUM['default_table_body_color_2']='$PHORUM[default_table_body_color_2]';\n";
      $data.="  \$PHORUM['default_table_body_font_color_2']='$PHORUM[default_table_body_font_color_2]';\n";
      $data.="  \$PHORUM['default_nav_color']='$PHORUM[default_nav_color]';\n";
      $data.="  \$PHORUM['default_nav_font_color']='$PHORUM[default_nav_font_color]';\n";
      $data.="\n";
      $data.="  // expand all the above into vars for legacy code.\n";
      $data.="  while(list(\$key, \$value)=each(\$PHORUM)){\n";
      if((int)phpversion()<4){
        $data.="    \$\$key=\$value;\n";
      }
      else{
        $data.="    \$\$key=\$PHORUM[\$key];\n";
      }
      $data.="  }\n";
      $data.="\n";

      $data.="  // database variables\n";
      $data.="  \$PHORUM['DatabaseServer']='$PHORUM[DatabaseServer]';\n";
      $data.="  \$PHORUM['DatabaseName']='$PHORUM[DatabaseName]';\n";
      $data.="  \$PHORUM['DatabaseUser']='$PHORUM[DatabaseUser]';\n";
      $data.="  \$PHORUM['DatabasePassword']='$PHORUM[DatabasePassword]';\n\n";

      $data.="\n";

      if(is_array($PHORUM["plugins"])){
        while(list($key, $value)=each($PHORUM["plugins"])){
          settype($value, "boolean");
          if($value) $data.="  \$PHORUM['plugins']['$key']=true;\n";
        }
      }
      $data.="\n";
      $data.="?>";

      if($fp = fopen($PHORUM["settings"], "w")){
          fputs($fp, $data);
          fclose($fp);
      } else {
          echo "Could not open file $PHORUM[settings].  Please check the file permissions.<br />";
          exit();
      }
    }

    if($forum!=''){
      $sSQL="Select * from ".$pho_main;
      if($forum!='all') $sSQL.=" where id=$forum";
      $q->query($DB, $sSQL);
      $rec=(object)$q->getrow();
      While(isset($rec->id)){
        if(!get_cfg_var("magic_quotes_runtime")){
          $rec->name = addslashes($rec->name);
          $rec->description = addslashes($rec->description);
          $rec->staff_host = addslashes($rec->staff_host);
        }
        $data ="<?php\n";
        $data.="  // $rec->name forum\n";
        $data.="  \$PHORUM['ForumId']=$rec->id;\n";
        $data.="  \$PHORUM['ForumActive']='$rec->active';\n";
        $data.="  \$PHORUM['ForumName']='$rec->name';\n";
        $data.="  \$PHORUM['ForumDescription']='$rec->description';\n";
        $data.="  \$PHORUM['ForumConfigSuffix']='$rec->config_suffix';\n";
        $data.="  \$PHORUM['ForumFolder']='$rec->folder';\n";
        $data.="  \$PHORUM['ForumParent']='$rec->parent';\n";
        $data.="  \$PHORUM['ForumLang']='$rec->lang';\n";
        if(!$rec->folder){
          $data.="  \$PHORUM['ForumDisplay']='$rec->display';\n";
          $data.="  \$PHORUM['ForumTableName']='$rec->table_name';\n";
          $data.="  \$PHORUM['ForumModeration']='$rec->moderation';\n";
          $data.="  \$PHORUM['ForumSecurity']='$rec->security';\n";
          $data.="  \$PHORUM['ForumEmailList']='$rec->email_list';\n";
          $data.="  \$PHORUM['ForumEmailReturnList']='$rec->email_return';\n";
          $data.="  \$PHORUM['ForumEmailTag']='$rec->email_tag';\n";
          $data.="  \$PHORUM['ForumCheckDup']='$rec->check_dup';\n";
          $data.="  \$PHORUM['ForumMultiLevel']='$rec->multi_level';\n";
          $data.="  \$PHORUM['ForumCollapse']='$rec->collapse';\n";
          $data.="  \$PHORUM['ForumFlat']='$rec->flat';\n";
          $data.="  \$PHORUM['ForumAllowHTML']='$rec->html';\n";
          $data.="  \$PHORUM['ForumAllowUploads']='$rec->allow_uploads';\n";
          $data.="  \$PHORUM['ForumUploadTypes']='$rec->upload_types';\n";
          $data.="  \$PHORUM['ForumUploadSize']='$rec->upload_size';\n";
          $data.="  \$PHORUM['ForumMaxUploads']='$rec->max_uploads';\n";
          $var = (!empty($rec->table_body_color_2)) ? "'$rec->table_body_color_2'" : "\$PHORUM['default_table_body_color_2']";
          $data.="  \$PHORUM['ForumTableBodyColor2']=$var;\n";
          $var = (!empty($rec->table_body_font_color_2)) ? "'$rec->table_body_font_color_2'" : "\$PHORUM['default_table_body_font_color_2']";
          $data.="  \$PHORUM['ForumTableBodyFontColor2']=$var;\n";
          $data.="  \$PHORUM['ForumShowIP']='$rec->showip';\n";
      $data.="  \$PHORUM['ForumAllowEMailNotify']='$rec->emailnotification';\n";
        }


        $var = (!empty($rec->body_color)) ? "'$rec->body_color'" : "\$PHORUM['default_body_color']";
        $data.="  \$PHORUM['ForumBodyColor']=$var;\n";

        $var = (!empty($rec->body_link_color)) ? "'$rec->body_link_color'" : "\$PHORUM['default_body_link_color']";
        $data.="  \$PHORUM['ForumBodyLinkColor']=$var;\n";

        $var = (!empty($rec->body_alink_color)) ? "'$rec->body_alink_color'" : "\$PHORUM['default_body_alink_color']";
        $data.="  \$PHORUM['ForumBodyALinkColor']=$var;\n";

        $var = (!empty($rec->body_vlink_color)) ? "'$rec->body_vlink_color'" : "\$PHORUM['default_body_vlink_color']";
        $data.="  \$PHORUM['ForumBodyVLinkColor']=$var;\n";

        $var = (!empty($rec->table_width)) ? "'$rec->table_width'" : "\$PHORUM['default_table_width']";
        $data.="  \$PHORUM['ForumTableWidth']=$var;\n";

        $var = (!empty($rec->table_header_color)) ? "'$rec->table_header_color'" : "\$PHORUM['default_table_header_color']";
        $data.="  \$PHORUM['ForumTableHeaderColor']=$var;\n";

        $var = (!empty($rec->table_header_font_color)) ? "'$rec->table_header_font_color'" : "\$PHORUM['default_table_header_font_color']";
        $data.="  \$PHORUM['ForumTableHeaderFontColor']=$var;\n";

        $var = (!empty($rec->table_body_color_1)) ? "'$rec->table_body_color_1'" : "\$PHORUM['default_table_body_color_1']";
        $data.="  \$PHORUM['ForumTableBodyColor1']=$var;\n";

        $var = (!empty($rec->table_body_font_color_1)) ? "'$rec->table_body_font_color_1'" : "\$PHORUM['default_table_body_font_color_1']";
        $data.="  \$PHORUM['ForumTableBodyFontColor1']=$var;\n";

        $var = (!empty($rec->nav_color)) ? "'$rec->nav_color'" : "\$PHORUM['default_nav_color']";
        $data.="  \$PHORUM['ForumNavColor']=$var;\n";

        $var = (!empty($rec->nav_font_color)) ? "'$rec->nav_font_color'" : "\$PHORUM['default_nav_font_color']";
        $data.="  \$PHORUM['ForumNavFontColor']=$var;\n";

        $data.="\n";
        $data.="  // expand the array into vars for legacy code.\n";
        $data.="  while(list(\$key, \$value)=each(\$PHORUM)){\n";
        if((int)phpversion()<4){
          $data.="    \$\$key=\$value;\n";
        }
        else{
          $data.="    \$\$key=\$PHORUM[\$key];\n";
        }
        $data.="  }\n";

        $data.="\n?>";
        if($fp = fopen("$PHORUM[settings_dir]/$rec->id.php", "w")){
            fputs($fp, $data);
            fclose($fp);
        } else {
            echo "Could not open file $PHORUM[settings_dir]/$rec->id.php.  Please check the file permissions.<br />";
            exit();
        }
        $rec=(object)$q->getrow();
      }
    }
  }

  function get_html_value() {
    global $html, $html_all,$html_style,$html_font,$html_li,$html_img,$html_a;

    if($html_all==1){
      $html="Y";
    }
    else{
      if($html_style==1){
        $html[]="b";
        $html[]="i";
        $html[]="u";
      }
      if($html_font==1) $html[]="font";
      if($html_li==1){
        $html[]="ol";
        $html[]="ul";
        $html[]="li";
      }
      if($html_img==1) $html[]="img";
      if($html_a==1) $html[]="a";
      if(is_array($html)){
        $html=implode("|", $html);
      }
      else{
        $html="N";
      }
    }
    return $html;
  }

  function QueMessage($m){
    global $message;
    if($message) $message.="<br />\n";
    $message.="$m";
  }

  function DropForum($f, $table) {
    global $q, $DB, $admindir, $pho_main, $uploadDir, $PHORUM;

    $sSQL = "Select count(id) as fornum from ".$pho_main." where table_name = '".$table."'";
    $q->query($DB, $sSQL);
    $rec=$q->getrow();
    if($rec["fornum"]==1) {
      $sSQL="DROP TABLE $table";
      $q->query($DB, $sSQL);
      $sSQL="DROP TABLE $table"."_bodies";
      $q->query($DB, $sSQL);
      $sSQL="DROP TABLE $table"."_attachments";
      $q->query($DB, $sSQL);
      $DB->drop_sequence($table);
    }
    $sSQL="Delete from ".$pho_main." where id = ".$f;
    $q->query($DB, $sSQL);
    @unlink("$PHORUM[settings_dir]/$f.php");

    // Remove attachments-dir.  Needs fix for portability.
    if (file_exists("$AttachmentDir/$table")) {
      @system("rm -rf $AttachmentDir/$table");
    }

  }


  function DropFolder($f){
    global $q, $DB, $admindir, $pho_main, $PHORUM;

    $sSQL="Select id, folder, table_name from ".$pho_main." where parent=$f";
    $q->query($DB, $sSQL);
    while($rec=$q->getrow()){
      if($rec["folder"]){
        DropFolder($rec["id"]);
      } else{
        DropForum($rec["id"], $rec["table_name"]);
      }
    }
    $sSQL="Delete from ".$pho_main." where parent=$f";
    $q->query($DB, $sSQL);
    $sSQL="Delete from ".$pho_main." where id=$f";
    $q->query($DB, $sSQL);
    @unlink("$PHORUM[settings_dir]/$f.php");

  }

  function GetForumPath($id){
    // don't global $PHORUM here
    $file=$GLOBALS["PHORUM"]["settings_dir"]."/$id.php";
    $path="";
    While(file_exists($file)){
        include $file;
        $path = (empty($path)) ? $PHORUM["ForumName"] : "$PHORUM[ForumName] : $path";
        $file=$GLOBALS["PHORUM"]["settings_dir"]."/$PHORUM[ForumParent].php";
    }

    return $path;
  }

  function check_security()
  {
    global $PHORUM, $f;
    if(empty($PHORUM["admin_user"]["forums"][0])){
        header("Location: $PHP_SELF");
        exit();
    }
  }

?>
