<?PHP
  // Blank out potentially dangerous per-forum values
  $ForumId=0;
  $ForumActive='0';
  $ForumName='';
  $ForumDescription='';
  $ForumConfigSuffix='';
  $ForumFolder='0';
  $ForumParent='0';
  $ForumLang='';
  $ForumDisplay='0';
  $ForumTableName='';
  $ForumModeration='';
  $ForumModEmail='';
  $ForumModPass='';
  $ForumEmailList='';
  $ForumEmailReturnList='';
  $ForumEmailTag='';
  $ForumCheckDup='0';
  $ForumMultiLevel='1';
  $ForumCollapse='1';
  $ForumFlat='1';
  $ForumStaffHost='';
  $ForumAllowHTML='N';
  $ForumAllowUploads='N';
  $ForumTableBodyColor2='#c0c0c0';
  $ForumTableBodyFontColor2='#000000';
  $ForumTableWidth='100%';
  $ForumNavColor='#C0C0C0';
  $ForumNavFontColor='#000000';
  $ForumTableHeaderColor='#000080';
  $ForumTableHeaderFontColor='#FFFFFF';
  $ForumTableBodyColor1='#FFFFFF';
  $ForumTableBodyFontColor1='#000000';

?>